name: Terraform Destroy

on:
  workflow_dispatch: {}

env:
  AWS_REGION: us-east-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_mysqluser: ${{ secrets.MYSQL_USER }}
  TF_VAR_mysqlpasswd: ${{ secrets.MYSQL_PASSWD }}

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: ⚪ Checkout repository
        uses: actions/checkout@v4

      - name: 🟢 Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.3

      - name: 💣 Destroy All Terraform Resources
        run: bash scripts/terraform-destroy.sh