name: Terraform Infrastructure CI

on:
  pull_request:
    branches: [ main ]          # PR에서 plan만
  push:
    branches: [ main ]          # main에 머지되면 apply

env:
  AWS_REGION: us-east-2

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Fmt
        run: terraform -chdir=cicd fmt -check

      - name: Terraform Init
        run: terraform -chdir=cicd init

      - name: Terraform Validate
        run: terraform -chdir=cicd validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform -chdir=cicd plan -no-color

      - name: Terraform Plan & Apply (main)
        if: github.ref == 'refs/heads/main'
        run: |
          terraform -chdir=cicd plan -out=tfplan
          terraform -chdir=cicd apply -auto-approve tfplan
