name: Terraform Infrastructure CI (Staging)

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

env:
  AWS_REGION: us-east-2

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform -chdir=cicd init

      - name: Terraform Validate
        run: terraform -chdir=cicd validate

      - name: Terraform Plan
        run: terraform -chdir=cicd plan -out=tfplan

      - name: Terraform Apply (staging)
        run: terraform -chdir=cicd apply -auto-approve tfplan
